version: '3'
services:
  db:
    image: docker.io/library/postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: My super secret.
      POSTGRES_DB: keycloak
    volumes:
      - ./data:/var/lib/postgresql/data:Z

  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Keycloak or bust.
      DB_VENDOR: postgres
      DB_ADDR: localhost:5432
      DB_DATABSE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: My super secret.
